name: donuz_dart_sdk
description: Donuz Dart SDK to comunicate with Donuz API
version: 1.0.0
homepage: https://github.com/HarleyItalo/donuz_dart_sdk
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 
  http: 
  intl:
  get_it: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail:
  
flutter:
