name: donuz_dart_sdk
description: Donuz Dart SDK to comunicate with Donuz API, Abstracting Logics of login and caching requests, on all avaliable modules exposed in Donuz API.
version: 1.0.7
homepage: https://github.com/HarleyItalo/donuz_dart_sdk
environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.1.0 <3.0.0'
  http: '>=0.13.6 <1.0.0'
  intl: '>=0.18.1 <1.0.0'
  get_it: '>=7.4.1 <8.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail:
  
flutter:
