const loginEstablismentJson = """{
    "status": 200,
    "mensagem": "Requisição realizada com sucesso",
    "token": "123",
    "permissoes": {
        "whatsapp": false,
        "push_notification": true,
        "inserirPontos": true,
        "pedidoListar": true,
        "produtoCadastrar": true,
        "presenteDadoListar": true
    },
    "estabelecimento": {
        "status": "contratou",
        "estabelecimento": "Encanto Sorvetes",
        "logo": "https://s3-sa-east-1.amazonaws.com/static.donuz.co/resources/uploads/lojaDePremios/logotipo/2234f25c8ec9cb3c8feb90e3f61b25c550b9logo.png",
        "banner": null,
        "cnpj": null,
        "imagem": null,
        "id_admin": 2234,
        "descricao_programa": "<p>Como Ganhar Pontos</p><p>Ao se cadastrar você já ganhou 10 pontos e a cada R1,00 real gastos ganhará 1 ponto.</p><p>Acesse a loja de prêmios com senha e login e complete seu cadastro em Meus Dados e ganhe mais 10 pontos!</p><p>Poderá ganhar pontos também ao indicar um amigo, você ganhará 10 em pontos quando o indicado fizer sua primeira compra.</p><p>Outra forma de ganhar pontos é respondendo nossa pesquisa de satisfação.</p><p>Resgate de pontos</p><p>Para efetuar a troca de Pontos no Programa por produtos ou descontos, o participante deverá alcançar o número mínimo de pontos exigidos.</p>",
        "regulamento": "<p>Este é um texto simples para verificar o regulamento.</p>",
        "gm_endereco_completo": "Rua São Paulo - Lourdes, Belo Horizonte - MG, Brasil",
        "numero": null,
        "bairro": "Centro",
        "cidade": "Belo Horizonte",
        "uf_estado": "MG",
        "url_acesso": "encantosorvetes",
        "frame_acesso": null,
        "complemento": "ap 101",
        "cep": null,
        "moeda": null,
        "latitude": "-19.9298473",
        "longitude": "-43.94294669999999",
        "distancia": null,
        "nome_idioma": null,
        "id_pais": 1,
        "email": "harley@donuz.co",
        "email_loja_premios": "harley@donuz.co",
        "pais": "Brasil",
        "telefone": "3133333333",
        "politicaPrivacidade": null,
        "politicaCookie": null,
        "id_filial": 2452,
        "id_usuario": 2477,
        "nome": "teste"
    }
}""";
