const settingsJson = '''{
    "configuracoes": {
        "id_config": 147,
        "estabelecimento_id": 2234,
        "cliente_pode_cadastrar": true,
        "cliente_pode_cadastrar_totem": true,
        "habilitar_codigo_pontuavel": false,
        "cadastro_campo_data_nascimento": false,
        "cadastro_campo_telefone": false,
        "cadastro_campo_celular": false,
        "cadastro_campo_endereco": false,
        "cadastro_campo_numero": false,
        "cadastro_campo_complemento": false,
        "cadastro_campo_estado": false,
        "cadastro_campo_cidade": false,
        "cadastro_campo_cep": false,
        "cadastro_campo_sobrenome": false,
        "cadastro_campo_escolaridade": false,
        "cadastro_campo_renda_mensal": false,
        "ordem_exibicao_produtos": "precoDonuz",
        "premios_por_pagina": "6",
        "campo_profissao": false,
        "campo_filial": false,
        "campo_tipo_cliente": false,
        "campo_time_torce": false,
        "campo_sexo": false,
        "validar_codigo_valor": false,
        "cliente_pode_curtir": false,
        "cliente_pode_compartilhar": false,
        "maximo_pontos_compartilhar": true,
        "descricao_compartilhamento": "Este é um teste de compartilhamento da loja de prêmios -- Felipe Donuz",
        "titulo_compartilhamento": "Encanto Sorvetes ",
        "logo_compartilhamento": "2234b0021af6e56b1c2a19685477483c35f8logofb.png",
        "css": ".infos-donuz { display:none !important ; }",
        "js": false,
        "cliente_pode_indicar": true,
        "valor_por_indicacao": 200,
        "valor_por_indicacao_cadastro": 10,
        "indicacao_tipo": "pontos",
        "indicacao_frequencia": "todas_as_compras",
        "habilitar_premio_valor_reais": true,
        "cadastro_codigo_cliente": false,
        "enviar_email_transacional": false,
        "cadastro_cpf": true,
        "habilitar_reset_premios": false,
        "pontos_preencher_cadastro": false,
        "pontos_nao_cliente": true,
        "bloquear_insercao_duplicada": true,
        "cadastro_campo_email": false,
        "pode_pontuar_por_valor_fixo": true,
        "valor_pontos_fixo": 50,
        "recorrencia": 90,
        "validade_voucher": 13,
        "habilitar_pontuacao_inteira": false,
        "tagplus_integracao_cadastrar": false,
        "habilitar_validar_cadastrar_codigos_pontuaveis": true,
        "categoria_ativa": false,
        "categoria_verificar": false,
        "categoria_usar_validade": false,
        "tagplus_integracao_regra": false,
        "desabilitar_emails": false,
        "max_venda": true,
        "campo_codigo_cliente_representa": false,
        "url_android": false,
        "url_ios": false,
        "onesignal_id": false,
        "onesignal_token": false,
        "verbo_clientes": null,
        "verbo_cliente": null,
        "galax_hash": false,
        "galax_id": false,
        "desabilita_resgate_cliente_nao_indicou": false,
        "habilitar_doacao": true,
        "email_proprio": false,
        "id_crm_externo": 2649,
        "max_insercao_dia": 2000,
        "habilita_qrcode_checkin": false,
        "habilitar_ofertas": false,
        "bloquear_controle_duplicado": false,
        "app_cartao_fidelidade": false,
        "quantidade_selos": 10,
        "configuracao_automatica": "1",
        "habilitar_insercao_nfce": true,
        "nfce_all_cnpj": true,
        "mimoAtivo": false,
        "campos_adicionais": [
            {
                "id_campo_adicional": 763,
                "campo": "teste campo adicional",
                "tipo": "text"
            },
            {
                "id_campo_adicional": 865,
                "campo": "teste select",
                "tipo": "select",
                "opcoes": [
                    {
                        "id_campo_adicional_opcao": 2004,
                        "opcao": "a"
                    },
                    {
                        "id_campo_adicional_opcao": 2005,
                        "opcao": "b"
                    },
                    {
                        "id_campo_adicional_opcao": 2006,
                        "opcao": "c"
                    }
                ]
            }
        ]
    }
}''';
