const getPrizeByIdJson = """{
    "prize": {
        "id_produto": 11056,
        "estabelecimento_id": 2234,
        "produto_controle": "cf0b14a6ec4f9c9ae87967900a957433",
        "produto": "Açaí com sorvete",
        "categoria": null,
        "subcategoria": null,
        "des_breve": "                                                                                                                                                                                                                                              ",
        "subcategoria_old": null,
        "tipo_de_resgate": null,
        "regras": "                                                                                                                                                                                                                                                 ",
        "status": "1",
        "precoDonuz": 90,
        "imagemPrincipal": "https://s3-sa-east-1.amazonaws.com/static.donuz.co/resources/uploads/lojaDePremios/premioImagem/201701271349051581183370.jpg",
        "imagemApp": null,
        "precoReais": 20,
        "peso": null,
        "altura": null,
        "largura": null,
        "comprimento": null,
        "codigo": null,
        "tags": null,
        "data_publicacao": "2019-12-17",
        "estoque": null,
        "estoque_padrao": null,
        "data_atualizacao": "2022-05-04 10:48:35",
        "visibilidade": 1,
        "tamanho": null,
        "doacao": null,
        "resgate_unico": null,
        "deleted": 0,
        "giftcard_value": null,
        "parceiro_giftcard": null,
        "cupom_id": null,
        "imagensAdicionais": [
            null,
            null,
            null,
            null,
            null
        ]
    }
}""";
